basePath: /
host: localhost:8081
info:
  contact: {}
  description: This is a sample server for an authentication microservice.
  title: Auth Microservice API
  version: "1.0"
paths: {}
swagger: "2.0"
